### ISSUE TITLE
Hops logo

### ISSUE THREAD

**Issue by rudeworks** [xing/hops#10]
Felt like giving Hops a slightly different image. Tell me what do you think about these options:

![hops-logo](https://cloud.githubusercontent.com/assets/140042/14559574/ff50d072-0309-11e6-87e1-ce2c71dd568b.png)

**Comment by rcsole** [comment]
Very cool! I personally like the bottom right one best.

**Comment by dmbch** [comment]
Yeah, nice and xingy! For me, it would be top right, though.

**Comment by rudeworks** [comment]
I'm pro bottom-left, but I guess we could post a doodle or something next week and chose like this is a democracy 😄

**Comment by dmbch** [comment]
I'll never be [BDFL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life), right? :wink:

**Comment by matthias-reis** [comment]
+1 for the top right one ...

**Comment by TobiasKrogh** [comment]
👍 for top right

**Comment by rudeworks** [comment]
ok seems like there's a clear winner

**Comment by naoisegolden** [comment]
top right +1 

(xing doesn't do shadows, plus the left one looks like an inverted artichoke 😜 )

**Comment by rudeworks** [comment]
Top right then, already on PR #12 💯
