### ISSUE TITLE
How to deep link to the company page in Xing iOS App?

### ISSUE THREAD

**Issue by Mikilll94** [xing/hops#1034]
@herschel666
In #1017 you have told me how to deep link to the specific profile in the Xing iOS app. Thanks for that :) But I want to know, how to deep link to the specific **company** page.

I.e. I want to deep link to Google page
https://www.xing.com/companies/googlegermanygmbh

How to achieve that?

I was trying `xing://companies/googlegermanygmbh` but this is not working.

**Comment by herschel666** [comment]
@Mikilll94 Sorry, but there's no public listing of available schemes by intention.
