### ISSUE TITLE
Run hops multithreaded

### ISSUE THREAD

**Issue by tjwelde** [xing/hops#1086]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

To leverage our servers fully, we would like to run multiple instances of hops in a container.
We tried using `pm2-runtime`, but since hops relies on the command line arguments, it fails because of unknown arguments (the ones you need for `pm2-runtime`)

## Proposed solution

Make it able to run hops via a custom js entry file, instead of using the cli tool.
OR
Document the best practices of running hops multithreaded in production.

PS:
How do you as maintainer of this repo run hops in production?

**Comment by ZauberNerd** [comment]
Hi @tjwelde we are running Hops in Kubernetes and/or AWS Lambda and we have only one Hops instance per pod.

If you need to have multiple instances per container you could look into starting Hops multiple times on different ports (can be overridden via environment variable `PORT`) and use a reverse proxy to route requests in a round-robin fashion to them (for example nginx).

**Comment by tjwelde** [comment]
Hey @ZauberNerd, we were thinking about a similar solution, but I got it to work with `pm2`, by making a start file, which sets the `process.argv` array to the correct options manually. It's a bit hacky, but works without adding more than a few lines of code.

How do you leverage all CPUs on your kubernetes servers?

**Comment by ZauberNerd** [comment]
We run one app per pod (and also only request one CPU per pod), therefore we can leverage more CPUs by scaling through the pods.

**Comment by tjwelde** [comment]
That makes sense. I will discuss this with our devops guy. Thanks!
