### ISSUE TITLE
Possibility to switch off SSR

### ISSUE THREAD

**Issue by tjwelde** [xing/hops#1096]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

When something is breaking in the app, it is difficult to debug the issue, because of the SSR.

## Proposed solution

Deactivate SSR to debug the issue in the browser.
Alternative: document debugging of code on server-side.

**Comment by ZauberNerd** [comment]
Hi @tjwelde you can disable server-side data fetching by setting `allowServerSideDataFetching` or `shouldPrefetchOnServer` to `false`: https://github.com/xing/hops/blob/master/DOCUMENTATION.md#settings-1 which would only render the initial tree on the server.
If you want to prevent that too, a workaround (for debugging purposes) could be to have a root component that renders its children only on `componentDidMount` which would result in your entire app only being rendered on the client.

**Comment by tjwelde** [comment]
ah ok, will try that out, thanks!
