### ISSUE TITLE
@@toStringTag in browserWhitelist

### ISSUE THREAD

**Issue by tjwelde** [xing/hops#1097]
## This is my intent (choose one)

- [x] I want to report a bug
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

After the upgrade to hops v12, I get following error:
```
The property "@@toStringTag" does not exist. Did you forget to add it to the browserWhitelist of your Hops config?
```
I tried adding it to `browserWhitelist`, but it didn't work.

It seems to be related to `prop-types`. Internally, the `isSymbol` function there tries to do following
```
if (propValue['@@toStringTag'] === 'Symbol') { ... }
```
which triggers the proxy getter in the `warnOnIncompleteBrowserWhitelist`, which can't handle that

## Proposed solution
Good question. I don't think just adding an exception for this solves the problem, because it is `prop-types`, specific and it could warn on other setups, still. 
We could expose the keys in the hops config and check, if they would be available at all, but this could be a security issue.

**Comment by herschel666** [comment]
@tjwelde Moin. It's not `'@@toStringTag'`, that's missing on the `browserWhitelist`. That's just what the `Proxy` thinks is about to be retrieved. Did you — by any chance — set a `Map()` as a config value in the Hops config?

**Comment by tjwelde** [comment]
No, I didn't. I am pretty sure, it is because of facebook/prop-types, which we are using. This line seems to be the culprit: https://github.com/facebook/prop-types/blob/e32c4900f5ab5fd3acea93e9d2f0d09e4a2f2ceb/factoryWithTypeCheckers.js#L533

**Comment by ZauberNerd** [comment]
Could it be that you are using `withConfig` (or passing the config object through props) and then the config object is being checked by prop-types?
And that then leads to the proxy saying the property might be missing. The proxy is just a helper, to remind you during development to whitelist any properties in the `browserWhitelist` that you may access from the client build.

**Comment by tjwelde** [comment]
Yes, that is exactly what we are doing.

**Comment by tjwelde** [comment]
thanks for fixing it
