### ISSUE TITLE
Forward and respect webpack magic comments

### ISSUE THREAD

**Issue by KnisterPeter** [xing/hops#1157]
We've got a few questions about how to prefetch / preload dynamically imported chunks with `importComponent`.
Right now untool drops these comments in the babel plugin and the server-side rendering does not respect such comments.
We should:
- tweak our babel plugin to keep comments in dynamic imports
- tweak our assets plugin to attach meta information about which chunks to preload/prefetch
- tweak our server-side rendering to add prefetch/preload resource hints

## Additional Info

Moved from https://github.com/untool/untool/issues/581

**Comment by herschel666** [comment]
Released with [Hops v12.3.0](https://github.com/xing/hops/releases/tag/v12.3.0).
