### ISSUE TITLE
Hot Reloading not working with default config

### ISSUE THREAD

**Issue by sirech** [xing/hops#133]
I'm trying to use the serve configuration with hops 2.1.0. When I update a file, it tries to recompile but I get the following error:

    Syntax error: Unexpected token <

It seems that the hot-update.json file contains the template again. I was able to fix it by adding the following to the `etc/webpack.serve.js` file provided by *Hops*:

    output: {
      publicPath: 'http://localhost:8080/'
    },

worth noting that I had a similar problem with hops 1.0.0, and was able to fix in a similar way

**Comment by dmbch** [comment]
Unfortunately, I'm unable to reproduce this issue (hops 2.1.0, node 7.3.0). Can you please share a bit more info on your specific setup? Or do you have a public project I could take a look at?

**Comment by sirech** [comment]
I have the same versions of node and hops, and I am using the default scripts as much as possible. The repo is this one: https://github.com/sirech/shelf

**Comment by dmbch** [comment]
@sirech: Sorry for the long delay - we have decided to reorient hops quite fundamentally and I was busy implementing the required changes. A fix for the issue that you reported, however, is included: https://github.com/xing/hops/blob/master/etc/develop.js#L24
