### ISSUE TITLE
hops-webpack does an automatic clean

### ISSUE THREAD

**Issue by KnisterPeter** [xing/hops#1419]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

`hops-webpack` does an automatic clean of the dist folder on start of a build.
This features does forbid pre build scripts which prepare something in the dist folder, not related to hops but to the build created.

## Proposed solution

I would like to propose an a cli flag (e.g. `--clean`) which has a default value of `true` to maintain current compatibility.
This flag could be set to false (e.g. `--clean=false` or `--no-clean`) to prevent this behaviour.

**Comment by ZauberNerd** [comment]
@KnisterPeter we already have such a flag: https://github.com/xing/hops/blob/93959a4c64fe945c207867bd46e87a7d11f6cbdd/packages/webpack/mixins/build/mixin.core.js#L108-L113
