### ISSUE TITLE
no assets included due to webpack-manifest-plugin package update

### ISSUE THREAD

**Issue by robin-drexler** [xing/hops#206]
`hops-config` requires `webpack-manifest-plugin@^1.2.1`.
We ran `yarn upgrade` which surprisingly (at least for me) also appears to upgrade supdependencies even when dependencies are already at the latest version.

Running the upgrade caused an upgrade of `webpack-manifest-plugin` to version `1.3.0`, which then causes hops to not include assets in the template anymore.

The release notes for [1.3.0](https://github.com/danethurber/webpack-manifest-plugin/releases/tag/v1.3.0) also state: `make sure manifest writes don't overlap` which sounds suspicous.

We only tested dev mode.

**Comment by dmbch** [comment]
Thanks! This ought to be fixed in #207 - https://github.com/xing/hops/pull/207/commits/f079111629ea1fce4496ee3591689ebb924281c1

PTAL

**Comment by dmbch** [comment]
Fixed in hops-config v6.2.2
