### ISSUE TITLE
Flowtype typecheck babel issue

### ISSUE THREAD

**Issue by rcsole** [xing/hops#23]
I've been experimenting with the typecheck babel plugin for the flow syntax
and I've ran into this issue, which seems big and it's unclear if it will be fixed
at all.

https://github.com/codemix/babel-plugin-typecheck/issues/134

Maybe we should consider not using typecheck and instead just provide
`babel-plugin-syntax-flow` and `babel-plugin-transform-flow-strip-types`?

**Comment by dmbch** [comment]
Thanks for bringing this up! I'll have to read up on this issue.

**Comment by dmbch** [comment]
@rcsole Could you give me an example (maybe a gist) to reproduce the issues you were experiencing?

**Comment by phpnode** [comment]
FYI this is fixed now

**Comment by dmbch** [comment]
@phpnode Thanks for letting us know!
