### ISSUE TITLE
Upgrade node-mocks-http

### ISSUE THREAD

**Issue by dmbch** [xing/hops#232]
Due to a [vulnerability](https://nodesecurity.io/advisories/526) found in one of its dependencies, we'll have to upgrade `node-mocks-http` as soon as [this PR](https://github.com/howardabrams/node-mocks-http/pull/147) is merged and a [new release](https://www.npmjs.com/package/node-mocks-http) (<1.6.5) is available.

**Comment by ZauberNerd** [comment]
Fixed by #240
