### ISSUE TITLE
Improve developer experience with hops-log

### ISSUE THREAD

**Issue by matthias-reis** [xing/hops#261]
## This is my intent (choose one)

- [ ] I want to report a bug
- [ ] I want to request a feature or change
- [x] I want to provide or change a feature

## The problem

The cli output throughout all cli parts is unfortunately not really consistent combining blank `console.log` statements with outputs of other parts like webpack.

## Proposed solution

I'd like to work on that and create a low level logging solution that 
- knows the levels `debug`, `info`, `warn` and `error`
- shows who is responsible for the current output (scope)
- can output debug level messages with the command line parameter -v
- can calculate elapsed times that show optimization potential (like `build took 42.2s`)
- is portable into external additional build tools 
- remains compatible to ci tools like travis and jenkins

**Comment by dmbch** [comment]
:rocket: Yes, please!

Quick question: what do you mean with CI tool compat?

**Comment by matthias-reis** [comment]
Avoiding command line loading indicators and progress bars, that create clutter in typical command line outputs of ci tools.

**Comment by dmbch** [comment]
Great! :thumbup:

We might want to check out CI-info for that: https://www.npmjs.com/package/ci-info

**Comment by ZauberNerd** [comment]
This is related to #502.

We have decided to use `console.log` for simple messages and are using [debug](https://www.npmjs.com/package/debug) for debugging output - can we close this issue now?
