### ISSUE TITLE
Give devServer config higher priority

### ISSUE THREAD

**Issue by ghost23** [xing/hops#266]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

In the server.js:

https://github.com/xing/hops/blob/v7.4.0/packages/build/server.js#L22

currently, after the devServer config options there is an additional object (the one with the after function and the watchOptions). This way, it is impossible to override that functionality. For example, you are always stuck with the rewrite:

https://github.com/xing/hops/blob/v7.4.0/packages/build/server.js#L24

even if you don't want to use that.

## Proposed solution

I would like to propose to simply change the order here:

https://github.com/xing/hops/blob/v7.4.0/packages/build/server.js#L22

from:
```Object.assign({}, config.devServer, { after: .... })```
to:
```Object.assign({}, { after: .... }, config.devServer)```

It wouldn't affect existing setups (nobody currently could have provided his/her own after: function, it would have been overridden)

(cc: @mjacobus)

**Comment by dmbch** [comment]
Sounds good! Would you like to provide a PR yourself?

**Comment by ghost23** [comment]
Yes, I will.

**Comment by dmbch** [comment]
Cool, thanks! 🚀

Please remember to add your info to the contributors section in the main `package.json` file 💡

**Comment by ghost23** [comment]
Done

**Comment by dmbch** [comment]
Thanks! 

Fixed in https://github.com/xing/hops/blob/v7.4.1/packages/build/server.js#L22
Released as hops-build v7.4.1: https://www.npmjs.com/package/hops-build
