### ISSUE TITLE
ES6 Modules

### ISSUE THREAD

**Issue by rcsole** [xing/hops#28]
I find myself creating a longer and longer regex if I want to import ES6
modules. Maybe we could add an option like `babelES6` which should
contain an array of folder not to be ignored by babel?

I find that `babelIgnore` containing also the part of the regex that
decides which ones NOT to ignore is sort of confusing. Here's what
I'm proposing:

```js
// lib/config.js
module.exports = overrideConfig({
  // ...
  babelIgnore: /node_modules\//,
  babelInclude: ['es-']
  // ...
})

// webpack.base.js
// ...
{
  test: /\.js$/,
  loader: 'babel',
  exclude: new RegExp(`${config.babelIgnore}${config.babelInclude.map((i) => `(?!${i})`).join('')}`)
}
// ...
```

**Comment by rcsole** [comment]
I think I'm closing in... It seems like the way our `render` functions work,
we're recreating the `store` on every update, which should not be the
case. Some issue that helped me track this down:

https://github.com/reactjs/react-router-redux/issues/305
https://github.com/reactjs/react-redux/issues/259

**Comment by dmbch** [comment]
I guess overriding the config in `package.json` or `.babelrc` does not currently work, right? It ought to, though, so I think you might have hit a bug there.

**Comment by rcsole** [comment]
Actually that comment was supposed to go in #29, my bad.

**Comment by rcsole** [comment]
@dmbch overriding the config in `hopsrc.js` works though

**Comment by dmbch** [comment]
Yeah, I expected as much. But I'd rather like to support the usual babel way of handling it. It's actually quite [nifty](https://babeljs.io/docs/usage/babelrc/).

**Comment by dmbch** [comment]
Switching to Babel's native config mechanism turns out to be nontrivial: We'll need to wait until this [bug](https://phabricator.babeljs.io/T6726) gets resolved, I guess. Currently, the `only` and `ignore` options in .babelrc and package.json are being ignored in cli and babel-register.

@rcsole: Would passing in an array of regexes help you for now? Both babel-register and webpack loader config ought to work with those.

**Comment by rcsole** [comment]
I think that would be a good solution, yes!

**Comment by dmbch** [comment]
Since #60 only webpack is used for transpilation - this issue ought to be sufficiently worked around, now. @rcsole please reopen if you object.
