### ISSUE TITLE
unable to use getUserConfirmation of BrowserRouter

### ISSUE THREAD

**Issue by Xiphe** [xing/hops#292]
## This is my intent (choose one)

- [x] I want to request a feature or change

## The problem

Given I have a Form
When the user enters data in the form
And navigates away without saving
Then I want to display a warning "Do you really want to discard..."

**BUT** I can not do this since [the implementation of the BrowserRouter](https://github.com/xing/hops/blob/master/packages/react/dom.js#L24-L29) does not allow me to set a custom [`getUserConfirmation`](https://reacttraining.com/react-router/web/api/BrowserRouter/getUserConfirmation-func)

## Proposed solution

hops-react should provide a way for me as a consumer to provide navigation guards.

Since I'm still not familiar with the intend/concept of the context api I find it hard to propose how to do that exactly.

**Comment by ZauberNerd** [comment]
@Xiphe you could just import the `ReactContext` and extend it by overwriting the `enhanceElement` method:
```javascript
import { BrowserRouter } from 'react-router-dom';
import hopsConfig from 'hops-config';
import { render, combineContexts, ReactContext } from 'hops-react';

class MyReactContext extends ReactContext {
  enhanceElement(reactElement) {
    return (
      <BrowserRouter basename={hopsConfig.basePath} getUserConfirmation={getConfirmation}>
        {reactElement}
      <BrowserRouter>
    );
  }
}

render(<MyApp />, combineContexts(MyReactContext));
```

**Comment by dmbch** [comment]
@Xiphe does [this](https://github.com/xing/hops/tree/improved-readmes/packages/react#render-contexts) shed some light on the current context implementation?

**Comment by Xiphe** [comment]
@ZauberNerd, your snippet breaks server side rendering since `enhanceElement` is applied on both: server and browser. The `BrowserRouter` can not be rendered on the server.

Next step for me: adding a platform switch in my app - wondering why i'm using hops-react at all.

**Comment by dmbch** [comment]
@Xiphe please check out #298 - I think that feature ought to enable you to achieve what you need without having to differentiate between client and server. From what I gather from StaticRouter's docs, it should ignore the `getUserConfirmation` prop.
