### ISSUE TITLE
aws config leaks into client bundle 

### ISSUE THREAD

**Issue by robin-drexler** [xing/hops#319]
## This is my intent (choose one)

- [x] I want to voice a concern
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem
The entire aws config can be found in the main.js because it is part of hops-config which gets inlined into the bundle.
This includes possibly confidential data such as certificateArn or information about the projects folder structure. 

## Proposed solution
If it is agreed upon that this rather suboptimal, we could allow to blacklist keys in hops-config that will not be part of the client bundle. `aws` could be one of the defaults.

**Comment by dmbch** [comment]
@ZauberNerd would you mind chiming in..? ;)

**Comment by ZauberNerd** [comment]
With the new config mechanism: https://github.com/xing/hops/commit/af402cea12c0e28270e260f145e237f62862bf26 we could just rename the aws config into `_aws` and be done with it, no?
In any case, I'm not sure that the information that can currently be accessed through `hops-config` would be considered confidential: https://github.com/xing/hops/tree/master/packages/lambda#available-options-through-hops-npm-config

**Comment by dmbch** [comment]
Yes, you are completely right: prefixing with `_` will indeed exclude the AWS config from the browser build - and the the data currently exposed does not appear to be sensible.

I think using the `_aws`-approach is the Right Thing (TM), anyway.
