### ISSUE TITLE
hops-graphql: getDataFromTree may not work with all kinds of apps

### ISSUE THREAD

**Issue by Xiphe** [xing/hops#324]
## This is my intent (choose one)

- [x] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

#### Observation

In the past I used apollo client without `hops-graphql` and just with the basic apollo features and everything worked great.
Now I try to migrate to `hops-graphql` and suddenly my ssr does not work anymore because values in react context are missing.

#### Thesis

It seems as if the rendering routine in [`getDataFromTree`](https://www.apollographql.com/docs/react/recipes/server-side-rendering.html#getDataFromTree) does not work well with `React.cloneElement` and/or Reacts context API.

#### Debugging

I disabled [ssr mode](https://www.apollographql.com/docs/react/recipes/server-side-rendering.html#skip-for-ssr) and tried to find the root cause for this but failed and will now give up after two hours.

I also failed to isolate the problem in a reproducible state.

## Proposed solution

In our use-case we do not need graphql queries to be run on the server since the data is highly user-specific and we use static pre-build-ssr and not dynamic ssr.

Therefore I propose to add an option to disable the ssr pre-fetching.

**Comment by dmbch** [comment]
Thanks for your report - and your patience! It would be great if you could provide a simple test case for us to investigate. Lacking that, we probably will not be able to be of a lot of assistance with debugging, but we will investigate your proposal (i.e. global `ssr` flag).

That being said, you could probably extend `GraphQLContext` and override the default [`getTemplateData`](https://github.com/xing/hops/blob/98b1c791c1528091e6667e0b0dd0717b49615e32/packages/graphql/node.js#L23) method. Would that help in your case?

**Comment by MikeBild** [comment]
Is a small modification like:

https://github.com/xing/hops/blob/98b1c791c1528091e6667e0b0dd0717b49615e32/packages/graphql/node.js#L17

```javascript
ssrMode: common.ssrMode || true
```

https://github.com/xing/hops/blob/98b1c791c1528091e6667e0b0dd0717b49615e32/packages/graphql/lib/common.js#L23

```javascript
  enhanceClientOptions: function(options) {
    return Object.assign({}, options, {
      link: options.link || this.createLink(),
      cache: options.cache || this.createCache(),
      ssrMode: options.ssrMode
    });
  },
```

on option?

**Comment by Xiphe** [comment]
There is no "simple test case" for this. As I said in the description, I only have the hypothesis that `getDataFromTree` and `cloneElement` somehow f-up together. 

I will not have the time to isolate the problem any further, sorry.

**Comment by dmbch** [comment]
@MikeBild what do you think about disabling server side data fetching altogether in static mode? See https://github.com/xing/hops/commit/32a89f0369b4b1d3f0f80a44b5aeb4afd42264f0.

**Comment by MikeBild** [comment]
🥇
