### ISSUE TITLE
Shorten CSS classes for production builds

### ISSUE THREAD

**Issue by HerrBertling** [xing/hops#325]
## This is my intent (choose one)

- [x] I want to provide or change a feature

## The problem

Currently, the CSS output for production builds is the same as for development environments (see https://github.com/xing/hops/blob/master/packages/build-config/sections/module-rules/postcss.js#L10 )

```js
var cssLoaderOptions = {
  importLoaders: 1,
  modules: true,
  localIdentName: '[folder]-[name]-[local]-[hash:8]',
  sourceMap: false,
};
```

Which results in quite long classnames. I'd like to obfuscate these way more to reduce the amount of characters shipped to users by `~70%` (rather wild guess, but `folder`, `name` and `local` should have around 6-8 characters like the hash in the end)

## Proposed solution

Provide another set of `cssLoaderOptions` for the production build with a different `localIdentName`, e.g. `[hash:base64:8]`.

I know this makes debugging in production a bit harder since the classnames are not that obvious. But I still think it's worth it shaving off quite some output :)

**Comment by 12finger** [comment]
@HerrBertling @matthias-reis 
regarding:
> .. still think it's worth it shaving off quite some output :

did you do the numbers already ?
i'd say, like out of the blue, that it wont yield a significant improvement for `prod`, as in many cases the GZIP running over it, will minimise the affect dramatically.

even Facebook, they don't seem to have a consistent approach to it 👻

looks like "Kraut & Rüben" oder: "Wie bei Hempels unterm Sofa!" ;)

![kcirtap amzok 2018-07-17 15-03-59](https://user-images.githubusercontent.com/1730022/42819150-fe619654-89d2-11e8-96d5-b0563a2d55fe.png)

**Comment by dmbch** [comment]
@12finger any specific reason you are asking? At least in our setting, it is (read: will be) rather trivial to shorten class names, so why not do it? Even with GZIP, nothing beats having less to stuff to transfer.

**Comment by dmbch** [comment]
Since we decided to close #327, I will close this, too.

**Comment by HerrBertling** [comment]
Na gut 😆
