### ISSUE TITLE
Add best practice for bootstrapping a redux application

### ISSUE THREAD

**Issue by DJCordhose** [xing/hops#357]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

Loading data when starting the application on the server side is a very common requirement. Often that data is needed to reasonably render an application in the first place. Hops already has the context lifecycle method bootstrap, which is too general however.

## Proposed solution

As Hops follows mainstream patterns, what you rather want to do is pass in a configuration for the redux extension that takes pairs of router paths and a list of of actions to perform before that both can be rendered. This approach is matches [the best practice in router v4](https://reacttraining.com/react-router/web/guides/server-rendering/data-loading).

**Comment by dmbch** [comment]
Good point, thank you! As you are describing a hash, but the link you posted mentions an array of route objects, I wonder which approach you favour..:

#### Hash
```js
const config = {
  actions: {
    '/': () => dispatch => getSomeData().then(result => dispatch({ payload: result}))
  }
}
```

#### Routes
```js
const config = {
  routes: [
    { 
      path: '/',
      component: Root,
      loadData: () => dispatch => getSomeData().then(result => dispatch({ payload: result}))
    }
  ]
}
```

Personally, I prefer the hash approach over the canonical one as it appears to be more flexible, especially given that the original only fetches data for the first match. With the hash approach, we could support multiple matches (for example for nested routes).

//cc @robin-drexler

**Comment by DJCordhose** [comment]
I would rather not generate routes from the same data structure as described in the v4 docs. That's why I also prefer the hash version. As we can not have double hashes as paths, I would propose to have an array of actions as an option, though.

**Comment by KingHenne** [comment]
> I would rather not generate routes from the same data structure as described in the v4 docs.

Why not? This has the benefit of being able to use `matchPath` from `react-router-dom`. It's also convenient if you are already using a routes config object with `react-router-config`. In this case you could even use [`matchRoutes`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-config/README.md#matchroutesroutes-pathname) to get a matching route object (or rather all matching route objects) and call `loadData` on it.

**Comment by DJCordhose** [comment]
I thought it would be against the philosophy of v4. If we have a central routing config, why not stick to v3?

**Comment by KingHenne** [comment]
I don’t think it is against the philosophy of v4. A routes configuration is used in the example you linked to and it is also used in `react-router-config`, which by the way also supports rendering a route component somewhere deep in your component tree. 

I just noticed this example in the [readme](https://www.npmjs.com/package/react-router-config#matchroutesroutes-pathname) which shows exactly the strength of this approach with regards to data loading:

```
const loadBranchData = (location) => {
  const branch = matchRoutes(routes, location.pathname)
 
  const promises = branch.map(({ route, match }) => {
    return route.loadData
      ? route.loadData(match)
      : Promise.resolve(null)
  })
 
  return Promise.all(promises)
}
 
// useful on the server for preloading data
loadBranchData(req.url).then(data => {
  putTheDataSomewhereTheClientCanFindIt(data)
})
 
// also useful on the client for "pending navigation" where you
// load up all the data before rendering the next page when
// the url changes
 
// THIS IS JUST SOME THEORETICAL PSEUDO CODE :)
class PendingNavDataLoader extends Component {
  state = {
    previousLocation: null
  }
 
  componentWillReceiveProps(nextProps) {
    const navigated = nextProps.location !== this.props.location
    const { routes } = this.props
 
    if (navigated) {
      // save the location so we can render the old screen
      this.setState({
        previousLocation: this.props.location
      })
 
      // load data while the old screen remains
      loadNextData(routes, nextProps.location).then((data) => {
        putTheDataSomewhereRoutesCanFindIt(data)
        // clear previousLocation so the next screen renders
        this.setState({
          previousLocation: null
        })
      })
    }
  }
 
  render() {
    const { children, location } = this.props
    const { previousLocation } = this.state
    
    // use a controlled <Route> to trick all descendants into 
    // rendering the old location
    return (
      <Route 
        location={previousLocation || location} 
        render={() => children}
      />
    )
  }
}
 
// wrap in withRouter
export default withRouter(PendingNavDataLoader)
 
/////////////
// somewhere at the top of your app
import routes from './routes'
 
<BrowserRouter>
  <PendingNavDataLoader routes={routes}>
    {renderRoutes(routes)}
  </PendingNavDataLoader>
</BrowserRouter>
```

**Comment by DJCordhose** [comment]
Not sure about that. Does not look quite mature to me, yet. Also that code is pretty complex IMHO. Maybe later when the approach is more mature and we have some real, obvious code as an example?

**Comment by dmbch** [comment]
Since we did not manage to address this until now, I will close this. Feel free to re-open if you feel we should.

Generally speaking, I feel that we are pivoting towards GraphQL as our main data access mechanism - and with `apollo-client`, we have a beautiful universal data fetching solution out of the box.
