### ISSUE TITLE
Re-Consider Support for Styled Components

### ISSUE THREAD

**Issue by dmbch** [xing/hops#359]
## This is my intent (choose one)

- [ ] I want to report a bug
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

No support for styled components...

## Proposed solution

Integrate https://github.com/foosbyte/kicker-trainer/tree/hops/packages/hops-styled-components and consider supporting arbitrary HTML head extensions.

**Comment by DJCordhose** [comment]
Looks good to me. We might want to scope the configuration for styled components and also add a styledComponentsExtension. Both should be trivial, though.

**Comment by ZauberNerd** [comment]
We now have https://github.com/xing/hops/tree/master/packages/styled-components
