### ISSUE TITLE
Integrate TypeScript Typings in Hops Repo

### ISSUE THREAD

**Issue by dmbch** [xing/hops#360]
## This is my intent (choose one)

- [ ] I want to report a bug
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

Some projects have written their own TypeScript typings for Hops, but keep them in their respective repositories.

## Proposed solution

Publish TypeScript typings together with Hops (as described in: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

We could use these typing as a starting point: https://github.com/foosbyte/kicker-trainer/tree/hops/typings

**Comment by DJCordhose** [comment]
Once we have moved code to ES6 we might also consider using ts-check for all the code as described here: https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files

**Comment by KingHenne** [comment]
In addition to the typings in https://github.com/foosbyte/kicker-trainer/tree/hops/typings this could be a starting point for `hops-redux`:

```ts
declare module 'hops-redux' {
  import {
    Options as ReactOptions,
    ReactContext,
    TemplateData,
  } from 'hops-react';
  import {
    GenericStoreEnhancer,
    Middleware,
    Reducer,
    ReducersMapObject,
    Store,
    StoreEnhancer,
    compose,
  } from 'redux';

  export interface Options {
    middlewares?: Middleware[];
    reducers?: ReducersMapObject;
  }

  export class ReduxContext<State> {
    public options: Options & ReactOptions;
    public reducers: ReducersMapObject;
    public composeEnhancers: typeof compose;
    public constructor(options?: Options & ReactOptions);
    public registerReducer<S>(namespace: string, reducer: Reducer<S>): void;
    public getStore(): Store<State>;
    public createStore(): Store<State>;
    public createEnhancer(): StoreEnhancer<State>;
    public composeMiddlewares(): StoreEnhancer<State>;
    public applyMiddlewares(): GenericStoreEnhancer[];
    public getMiddlewares(): Middleware[];
    public enhanceElement<P1, P2>(
      reactElement: React.ReactElement<P1>
    ): Promise<React.ReactElement<P2>>;
    public getTemplateData<P>(
      templateData: Partial<TemplateData>,
      rootElement: React.ReactElement<P>
    ): Promise<TemplateData>;
  }

  export function createContext(options?: Options & ReactOptions): ReactContext;
}
```

**Comment by DJCordhose** [comment]
Good starting point, but I do not think all the methods of the context should be public. Maybe protected?
