### ISSUE TITLE
Tests for render, extensions and createContext

### ISSUE THREAD

**Issue by DJCordhose** [xing/hops#363]
There should be tests making sure those use cases all work properly

```javascript
export default render(<App/>, {
  extensions: [reduxExtension({reducers})],
});

export default render(
  <App/>,
  createContext({reducers})
);

export default render(
  <App/>,
  createContext({redux: {reducers}})
);

export default render(
  <App/>,
  createContext()
);
```

**Comment by ZauberNerd** [comment]
We are nearing the Hops 11 release and for Hops 11 we don't use extensions / context anymore.
I'll close this issue for now, feel free to re-open it, if you think we are missing something.
