### ISSUE TITLE
Document bootstrapServer

### ISSUE THREAD

**Issue by KingHenne** [xing/hops#380]
## This is my intent (choose one)

- [x] I want to report a bug / Ask a question
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

I wanted to find out how the config option `bootstrapServer` is supposed to be used and couldn't find documentation on that. Is that internal API or should it be mentioned in [packages/config/README.md](https://github.com/xing/hops/blob/master/packages/config/README.md)?

## Proposed solution

If this is option is regarded as internal, comment and close this issue, otherwise please add an entry with a short description to the table in [packages/config/README.md](https://github.com/xing/hops/blob/master/packages/config/README.md).

**Comment by dmbch** [comment]
@KingHenne we are currently considering `boostrapServer` and `teardownServer` semi-private/unofficial APIs. We will probably replace/rename them in hops@11 - in any case, we will be adding appropriate documentation as soon as we have a final implementation.

**Comment by ZauberNerd** [comment]
We are nearing the Hops 11 release which won't have `bootstrapServer` anymore.
Instead we now have "core" mixins, that allow to configure the webpack configs / express server:
https://github.com/xing/hops/tree/master/packages/express#configureserverapp-middleware-mode-app-pipe-core
