### ISSUE TITLE
Include / Link installation instructions in README

### ISSUE THREAD

**Issue by heliosam** [xing/hops#395]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem
This was my very first attempt to use hops since a long time, and I realised that there isn't any reference to `yarn add global hops` or `npm install --global hops` other than `npx hops init ..` in the main README file, which is cool if you are starting a project from scratch, but what if I'm contributing to an existing project for the very first time or I don't use `npx` at all?

## Proposed solution
I think that splitting in the main README file
```
npx hops init ...
```
into
```
npm install --global hops | yarn add global hops
hops init ...
```
will make things more clear. If I'm an `npx` user I will know that I can save one command, if not I have all the information I need.

In fact this is included in https://github.com/xing/hops/tree/master/packages/cli, somehow hidden... I think it will help to have it in the main README, or at least link it from there.

What do you think?

**Comment by dmbch** [comment]
@heliosam thanks for raising this issue! What we wanted to document with that section was to provide the easiest way to set up a hops project, without having to install anything globally... That being said, how about adding a link to the [hops-cli README](https://github.com/xing/hops/tree/master/packages/cli#installation) to that section?

//cc @DJCordhose

**Comment by DJCordhose** [comment]
+1 for a link to the hops-cli README.

**Comment by ZauberNerd** [comment]
@heliosam we just released the next major Hops version hops@11 and completely rewrote the main readme (https://github.com/xing/hops/blob/master/README.md) therefore this issue should now be considered fixed :tada:
