### ISSUE TITLE
normalize.css on a config level?

### ISSUE THREAD

**Issue by rudeworks** [xing/hops#4]
I guess it's a good choice to always reset or normalize styles before start creating new ones, but I guess including normalize.css as a default is kind of opinionated.

I mean that I understand this things as a part of the end product and I guess Hops goes a little too far including normalize.css as a default way of reseting styles. I may prefer [sanitize.css](https://github.com/10up/sanitize.css) (which I do) or a plain old reset.css, or even a custom solution.

Maybe it's better to let the users chose the best for their app? What do you think?

**Comment by dmbch** [comment]
I think you're absolutely right. Does @matthias-reis fix from the [first pr](https://github.com/xing/hops/pull/1) work for you?

**Comment by TobiasKrogh** [comment]
Just to give some more context: https://github.com/xing/hops/pull/1 removed the default add of normalize css and allowed you to include those in your own project

A possible variant could be to install the `normalize.css` package and use it like so:

file `src/base-styles/normalization.css`:
```css
@import 'normalize.css';

body {
  /* my other main styles */
}
```

and reference it in `.hopsrc.js`:
```javascript
module.exports = {
  /* other configs */
  cssShared: ['./src/base-styles/normalization.css']
};
```

**Comment by rudeworks** [comment]
Why not just use [postcss-import](https://github.com/postcss/postcss-import) (or [postcss-simple-import](https://www.npmjs.com/package/postcss-simple-import)) to handle the importing from the ```node_modules``` folder? I know it adds another dependency, but I find it quite simpler to

```
npm install sanitize.css
```
and then just

```css
@import 'sanitize.css'
```
from my styles.

**Comment by matthias-reis** [comment]
@rudeworks Yes ... that's exactly what our pull request does. Instead of having a fixed normalize.css, you can handover any core style you want including e.g. bootstrap, sanitize or the xing globals coming from an internal npm and of course own styles on top.
