### ISSUE TITLE
Can not load css for external package

### ISSUE THREAD

**Issue by lipina** [xing/hops#418]
## This is my intent (choose one)

- [x] I want to report a bug
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

Following the [documentation](http://react-day-picker.js.org/docs/getting-started) for setting up the `react-day-picker` in my project I try to require styles usying `css-loader` like this: 
```
import "react-day-picker/lib/style.css";
```
but it doesn't work.

## Proposed solution

🤔

**Comment by dmbch** [comment]
Hey @lipina, thanks for this report! I am a afraid it appears that this might just be `hops`‘ current behavior: we are currently using `css-loader` with CSS modules for all CSS files.

As soon as we can merge #417 or #354 we will have a per-file opt-out for this behavior (see bc3a94a)

Could you temporarily include that component’s CSS locally in your project and wrap its class identifiers like so `:global(.xxx)` (see https://github.com/css-modules/css-modules/blob/master/README.md#exceptions)?

**Comment by dmbch** [comment]
This issue can now (finally) be resolved: https://github.com/xing/hops/releases/tag/v10.3.0

@lipina please verify.

**Comment by lipina** [comment]
It doesn't work for me unfortunately. 🤷‍♀️

I tried both `import "react-day-picker/lib/style.css";` and `import "react-day-picker/lib/style.css?global";`

**Comment by ZauberNerd** [comment]
This has been merged into master with #688 and will be included in the next release of Hops 11 RC.
