### ISSUE TITLE
npm test --coverage not working in related projects

### ISSUE THREAD

**Issue by matthias-reis** [xing/hops#43]
**Given**:
command line call

```
> npm test --coverage
```

package.json

```
"scripts": {
  "test": "hops test"
}
```

**Result**:
Test runs with coverage, but doesn't recognize test files and source files for analysis.

**Expected**:
Test detects all js files in the projects and can calculate the test coverage from the defined unit tests.

**Comment by dmbch** [comment]
Using a fresh project and clean install, things seem to work for me with hops@0.6.4 (both files in src and subfolders of src are being picked up and analyzed). We'll have to investigate further.

**Comment by dmbch** [comment]
As we recently removed coverage support from hops, I think it's safe to close this issue. @matthias-reis if you have any objections, please reopen.
