### ISSUE TITLE
Provide enhancer for store.

### ISSUE THREAD

**Issue by rcsole** [xing/hops#46]
One might want to use `redux-saga` instead of `redux-thunk` (for example),
would it be out of the scope of this project to allow for a custom store
enhancer?

**Comment by dmbch** [comment]
I don't think it needs to be - I'm currently thinking about some changes to the store/state utilities in hops, anyhow.

**Comment by rcsole** [comment]
Hmmm, OK. Cool, right now this is very opinionated as to how the store
should be constructed. Which is fine, but it doesn't allow for customization
of things like middleware.

**Comment by dmbch** [comment]
Did you see this new [branch](/xing/hops/tree/better-state-mgmt)..?

**Comment by rcsole** [comment]
No I didn't! That looks neat. I also missed the part where you can
provide your own `createStore` function, so I'm closing this as it's
not really relevant anymore.
