### ISSUE TITLE
postcss-cssnext should be replaced with postcss-preset-env

### ISSUE THREAD

**Issue by HerrBertling** [xing/hops#492]
## This is my intent (choose one)

- [x] I want to request a feature or change

## The problem

`postcss-cssnext` will be deprecated within the next days: https://github.com/MoOx/postcss-cssnext/issues/445 and should be replaced with `postcss-preset-env` according to the issue (=> https://preset-env.cssdb.org/ )

## Proposed solution

Investigate how to replace (and then replace) `postcss-cssnext`. Probably with `postcss-preset-env` and whatever else is needed.

**Comment by ZauberNerd** [comment]
This has been done in Hops 11 which is currently available as a release-candidate through the `next` npm tag.
