### ISSUE TITLE
Server side rendering. No js and css assets.

### ISSUE THREAD

**Issue by fuko-fabio** [xing/hops#494]
## This is my intent (choose one)

- [x] I want to report a bug
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

After hops upgrade to latest version server side rendering doesn't work properly. Lambda is serving html content but header doesn't contain links to css and js assets.

Last working config before upgrade:
```
"hops-config": "10.0.2",
"hops-express": "10.0.2",
"hops-lambda": "10.1.1",
"hops-react": "10.0.2",
"hops-redux": "10.0.2",
"hops": "10.0.2",
"hops-build": "10.1.0",
"hops-renderer": "10.0.2",
```

Generated html header before upgrade:
```
<title>XXX</title>
<meta data-react-helmet="true" charset="utf-8">
<meta data-react-helmet="true" name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1">
<link data-react-helmet="true" href="/assets/webpack/xxx/x_production-50ff1e0f4072ad4a.ico"
      rel="shortcut icon" type="image/ico">
<link data-react-helmet="true" rel="stylesheet"
      href="https://www.xxx.com/assets/frontend_minified/css/webfont-6ee69c71412d8bbc162bf9feaca16775.css">
<link rel="stylesheet" href="/assets/webpack/xxx/vendors~main-5fedbbdd8cb70701.css">
<link rel="stylesheet" href="/assets/webpack/xxx/main-1a81671368ee7942.css">
<script charset="utf-8" src="/assets/webpack/xxx/1-72357a93a5c6fadd.js"></script>
```
After upgrade
```
<title data-react-helmet="true">XXX</title>
<meta data-react-helmet="true" charset="utf-8">
<meta data-react-helmet="true" name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1">
<link data-react-helmet="true" href="/assets/webpack/xxx/xing_production-50ff1e0f4072ad4a.ico"
      rel="shortcut icon" type="image/ico">
<link data-react-helmet="true" rel="stylesheet"
      href="https://www.xxx.com/assets/frontend_minified/css/webfont-6ee69c71412d8bbc162bf9feaca16775.css">
```

**Comment by ZauberNerd** [comment]
@fuko-fabio since AWS Lambda uses the same server as `hops serve` - could you provide a few simple steps to reproduce this behaviour locally?

**Comment by dmbch** [comment]
@fuko-fabio any news with regards to this issue? Have you been able to troubleshoot it yourself or to produce some sort of test case?

**Comment by fuko-fabio** [comment]
Unfortunately when we use `hops serve` localy everything works fine. I wasn't able to reproduce this. Now we are trying again with latest versions and updated deployment script. I will come back to you when we check this.

**Comment by ZauberNerd** [comment]
@fuko-fabio you can also try to execute the following JS snippet (which basically does the same thing as AWS Lambda) in your application:
```javascript
require('hops-lambda/lambda').handler({
  requestContext: {
    path: '/'
  },
  path: '/'
}, {}, (error, response) => {
  if (error) {
    return console.error(error);
  }
  if (response.isBase64Encoded) {
    response.body = Buffer.from(response.body, 'base64').toString('utf-8');
  }
  console.log(response);
})
```

**Comment by ZauberNerd** [comment]
@fuko-fabio so this has now been resolved, right?
The problem was that the `./dist/` directory has been excluded from the lambda zip bundle, but the `stats.json` which contains information about which assets are available also lives inside the `./dist/` directory - therefore no JS and CSS assets have been rendered in the output.
