### ISSUE TITLE
Annotated source

### ISSUE THREAD

**Issue by rcsole** [xing/hops#5]
It might be a good idea to provide an annotated source in the example
app, instead of it being plain. Eg. comment what the decorator does,
`getSelector`, `createReducer`, etc...

Along with maybe a list of useful resources that might explain more in-depth
the tools and libraries this bundle includes.

Thoughts?

**Comment by naoisegolden** [comment]
+1

**Comment by dmbch** [comment]
Yes, definitely - and not just there. I think we need some sort of documentation at least for all hops components. Right now, I'm thinking along the lines of jsdoc extracted to markdown files that might be served as a Github wiki... Any thoughts..?

**Comment by rcsole** [comment]
Mostly I figured that given the fact that the example app might be used as
a template, it would be good to have it annotated in a way that makes it easy
to understand and get started.

An example would how rails configuration files are annotated when you first
run `rails new my-project`.

I do agree with having docs for all hops components though.

**Comment by rcsole** [comment]
Here's an example of what I meant.

https://github.com/rcsole/hops/commit/35eb8b8185263ae85dda7cd18266fdd6bc1387d5
