### ISSUE TITLE
Add log functionality

### ISSUE THREAD

**Issue by jhiode** [xing/hops#502]
## This is my intent (choose one)

- [ ] I want to report a bug
- [ ] I want to request a feature or change
- [x] I want to provide or change a feature

## The problem

Untool has removed most of the logging functionality.

## Proposed solution

Re-implement logging functionality.
Consider using https://github.com/winstonjs/winston.
Log information about started server (inspectServer) and maybe Webpack build output.
Provide a hook for other mixins to use and/or configure.

**Comment by ZauberNerd** [comment]
We have implemented basic logging using `console.log` in some of the mixins and are using winston for internal logging - can this issue be closed now?
