### ISSUE TITLE
hops-graphql

### ISSUE THREAD

**Issue by MikeBild** [xing/hops#589]
The *goal* is to be as simple as possible implementation of a FE data fetching layer independent *GraphQL query and mutation mocking/stubbing* package without affecting the BE infrastructure. 

GraphQL mock server should improve:

* FE developer productivity to provide faster component implementations by a FE driven GraphQL schema design approach
* FE developer independency by mocking/stubbing incomplete or new BE/GraphQL implementations
* E2E-Test productivity to provide faster execution time of BE related test scenarios

Depends on:
* Issue #597 (done)

Todos:
* add debug output

**Comment by ZauberNerd** [comment]
Closed via: 2acc7a7
