### ISSUE TITLE
`yarn test` get stuck on OSX

### ISSUE THREAD

**Issue by MikeBild** [xing/hops#594]
Test run get stuck on OSX (screenshot) and works correctly after everything has been reinstalled with

```bash
git clean -dfx
yarn install
```

<img width="745" alt="bildschirmfoto 2018-08-31 um 14 40 03" src="https://user-images.githubusercontent.com/179382/44912839-c8de2200-ad2b-11e8-954b-0c0c2c8a7fe1.png">

**Comment by MikeBild** [comment]
Known issue in [`ncp` package](https://github.com/AvianFlu/ncp/issues/131). Use `fs-extra` to fix.

**Comment by ZauberNerd** [comment]
Closed via: f6afebb
