### ISSUE TITLE
hops-graphql package APOLLO_IQRD <> APOLLO_IRQD

### ISSUE THREAD

**Issue by MikeBild** [xing/hops#597]
## This is my intent (choose one)

- [x] I want to report a bug

## The problem

mixin.server.js APOLLO_IQRD <>  mixin.browser.js APOLLO_IRQD

## Proposed solution

Rename `APOLLO_IQRD` and `APOLLO_IRQD` to `APOLLO_FRAGMENT_TYPES`.

I will prepare a PR to fix this issue.

**Comment by ZauberNerd** [comment]
Fixed in: 4b40d57
