### ISSUE TITLE
Code splitting -> wrong order

### ISSUE THREAD

**Issue by tjwelde** [xing/hops#618]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

When using hops-react, the vendor chunk is loaded _after_ the main chunk in production mode.
Development mode behaves correctly.

## Proposed solution

In `@untool/react/lib/template.js`, we could change the `renderCSS` and `renderJS` function to reverse the array, before joining it. But maybe the issue lies already in the accumulation step of `assetsByType`...

**Comment by tjwelde** [comment]
This might be another option: https://github.com/untool/untool/blob/fc24e027db507914596370ba4cd25ce953a2a2c8/packages/webpack/lib/plugins/assets.js#L35

**Comment by dmbch** [comment]
Thanks for this bug report, @tjwelde! The latest pre-release version of `hops-react` (11.0.0-rc.33) ought to already contain the upstream fix you linked to. Are you already running that version? If not, would you mind updating?

**Comment by tjwelde** [comment]
I am running an older version, indeed. Will try it out.

**Comment by tjwelde** [comment]
Thanks, it works!
