### ISSUE TITLE
Can't override getApolloLink

### ISSUE THREAD

**Issue by tjwelde** [xing/hops#619]
## This is my intent (choose one)

- [x] I want to report a bug
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

I want to override `getApolloLink` from `hops-graphql`.
I am doing it like this:

```
const { Mixin } = require('hops-mixin');
const { HttpLink } = require('apollo-link-http');

class GraphqlMixin extends Mixin {
  getApolloLink() {
    [...]
    return link;
  }
}

module.exports = GraphqlMixin;
```

As filename, I tried it with mixin.{server, browser, runtime}.js  
Other mixins in the same directory work.

## Proposed solution

My guess is, that my mixin is somehow prioritised less than the `hops-graphql` library, or I am doing something wrong.

**Comment by ZauberNerd** [comment]
@tjwelde I just tried to reproduce this and can confirm, that the mixin implementation is not being called.
I will investigate further.. :male_detective:
