### ISSUE TITLE
Loading presets implicitly should not be possible by default

### ISSUE THREAD

**Issue by saviomuc** [xing/hops#620]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem
Currently presets are loaded implicitly. While It's convenient it also introduces "magic" into the project and makes it hard to understand (without looking into the documentation) which presets are active (all presets which are installed via package.json) and which are not.

This might be easy to reason about when you only work with hops. 
But usually in bigger projects there will be multiple tools (babel, eslint, etc) where you expect to find all module specific configuration in module specific configs. 

Having config as an opt-in only increases confusion.

## Proposed solution
Enforce loading of presets via config file and not as an opt in in order to decrease confusion.

**Comment by dmbch** [comment]
@saviomuc thank you for your input! I think you raise some very valid concerns here.

The trade-off between explicitness and convenience is a very tricky one, though - and I would love to find out what @ZauberNerd has to add to this discussion: it was the two of us who came up with the feature in the first place.

**Comment by ZauberNerd** [comment]
@saviomuc we built this feature inspired by [parcel](https://parceljs.org/plugins.html#using-plugins), which also automatically discovers and enables all installed parcel plugins; and we thought that this is a nice feature which reduces configuration, especially in simple projects (in some cases it might be required to manually list the presets, for example when presets depend on one another or require to be loaded in a specific order).

But as we talked about this today in the office no one seems to have any particular opinion for keeping or removing this feature.

/cc @robin-drexler @jhiode

**Comment by saviomuc** [comment]
@ZauberNerd thanks for the reply. I guess the implementation on parcel's side stems from its `no configuration` philosophy and kinda makes sense in its scope. I also understand how it fits into hop's philosophy. What differs is that with hops `Some presets require (or allow) additional configuration.`. That enables four ways to configure hops:

1) Implicitely load presets
2) Explicitely load presets
3) Implicitely load presets and configure them
4) Explicitely load presets and configure them

This can potentially increase entropy and confusion imho. 🙈 Of course what option is being used depends heavily on the team. I personally prefer exactly one way

1) Explicitely load presets and configure them

While I like the idea of no config the reality is that a lot of projects moved to simpler configs and it makes it easier to just look into a common location for all config options. I.e in the current project I am working on.

![screen shot 2018-09-11 at 10 53 17](https://user-images.githubusercontent.com/1830601/45349570-e7f17500-b5b1-11e8-8876-1b26955a7a9c.png)


**Side note**
Also it should be clarified what `hops.presets` actually does. Will it actually disable automatic package discovery or is it just for the sake of documentation? 

i.e.
```
BEFORE
If you prefer, you can also explicitly list the presets that you want to use under the presets key in your application configuration.
=====
AFTER
If you prefer, you can also explicitly list the presets that you want to use under the presets key in your application configuration. This will disable automatic discovery of hops packages. 
```

**Comment by robin-drexler** [comment]
@saviomuc I really your idea of making it more explicit in the docs. 

Would you like to open a PR, so you get the well-deserved contribution? :)

Maybe you can replace `hops package` with `hops preset`, though.
