### ISSUE TITLE
Document how to extend `.babelrc`

### ISSUE THREAD

**Issue by saviomuc** [xing/hops#623]
## Document how to extend `.babelrc`

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem
Actually it's a question, at least I could not find the doc for it.
 In the project I am working on we use some specific plugins. I.e. raw loader for SVGs. Unfortunately I cannot find the docs to extend the `.babelrc`. Is there a specific way to extend it?

As far as I understand `hops`  only uses webpack (as opposed to a dedicated babelrc config) to pass in babel loaders. So the current way would be to create a `mixin.core.js` and extend the config for all targets (`develop`, `node`, etc.), right?

i.e.
```
configureTargetDevelop({jsLoaderConfig}) {
 jsLoaderConfig.options.plugins.push(
    require.resolve('babel-plugin-inline-react-svg'),
 );
}
```

 Is that the recommended way to do it?

## Proposed solution
As it's a question there is no solution, but maybe it would be a good idea to clarify `.babelrc` config in documentation.

**Comment by robin-drexler** [comment]
You're proposed solution is correct, @saviomuc.
We'll also make it more clear/prominent in the docs.

Thanks! :)

**Comment by saviomuc** [comment]
Ah I see. Thanks for clarification! =)
