### ISSUE TITLE
Error "Can't load undefined" after update to rc.35

### ISSUE THREAD

**Issue by saviomuc** [xing/hops#644]
## This is my intent (choose one)

- [x] I want to report a bug
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem
To benefit from recent commits we updated the project to use these dependencies:
```
    "hops": "v11.0.0-rc.35",
    "hops-graphql": "v11.0.0-rc.35",
    "hops-mixin": "v11.0.0-rc.35",
    "hops-preset-defaults": "v11.0.0-rc.35",
    "hops-react": "v11.0.0-rc.35",
```

Before we used:

```
"hops": "11.0.0-rc.27",
    "hops-graphql": "11.0.0-rc.28",
    "hops-mixin": "^11.0.0-rc.25",
    "hops-preset-defaults": "11.0.0-rc.27",
    "hops-react": "11.0.0-rc.27",
```

Since then I am getting an error `Skip: can't load undefined.` when executing the start script (`yarn start:dev`). My guess is that some config file / mixin (?) is required and not found. 
The folder structure for our mixins is:

```
mixins
└── webpack
    ├── mixin.core.js
    └── mixin.server.js
```

## Proposed solution
As I don't fully understand where the bug is coming from I don't have a proposed solution.

**Comment by ZauberNerd** [comment]
@saviomuc that is coming from the GraphQL mock server, which are currently in the process of refactoring: https://github.com/xing/hops/pull/642
You can ignore that message and after #642 is merged (and released) it won't appear again.

**Comment by saviomuc** [comment]
Okay. Thanks for the quick reply! I guess the issue can be closed then.
