### ISSUE TITLE
Section "Configuration" in README.md lacks information

### ISSUE THREAD

**Issue by saviomuc** [xing/hops#692]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem
Currently the documentation for the configuration points to https://github.com/davidtheclark/cosmiconfig whereas it would be much more helpful to have an actual list of supported keys like here: https://github.com/xing/hops/tree/master/packages/preset-defaults

## Proposed solution
Provide full list of default keys

**Comment by ZauberNerd** [comment]
@saviomuc we completely rewrote the main readme and just released hops@latest so this issue should now be fixed :tada:
