### ISSUE TITLE
Support React.lazy and Suspense

### ISSUE THREAD

**Issue by johannesbraeunig** [xing/hops#714]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

I'd like to lazy-load components and make use of Reacts newest features `React.lazy` and `<Suspense />` (https://reactjs.org/docs/code-splitting.html#reactlazy).

But react-dom or the implementation of it is not supporting it yet. If I implement it I get this warning:

`ReactDOMServer does not yet support Suspense.`

**Comment by robin-drexler** [comment]
Did you see the note in the docs stating that it does not work on the server yet?
```
Note:
React.lazy and Suspense is not yet available for server-side rendering
```

You'd have to ensure it's only rendered on the client if you want to try it already.

**Comment by robin-drexler** [comment]
However, hops comes with its own [`Import`](https://github.com/untool/untool/tree/master/packages/react#importmodule-exportname) component (note the capital `I`) which will assist with code splitting and even works on the server.

It's not `Suspense`-compatible (yet), though.

**Comment by dmbch** [comment]
It *might* be possible to transpile `React.lazy` to something we can actually deal with server-side and re-use the asset determination mechanism used with `Import`. Additionally, we will have to come up with a way to deal with `Suspense`: for example, we might be able to simply replace it with plain `Fragment`s for SSR.

**Comment by Daniela0106** [comment]
> Did you see the note in the docs stating that it does not work on the server yet?
> 
> ```
> Note:
> React.lazy and Suspense is not yet available for server-side rendering
> ```
> You'd have to ensure it's only rendered on the client if you want to try it already.

Unfortunately, it's true by now, not yet supported on SSR... https://reactjs.org/docs/code-splitting.html

**Comment by ZauberNerd** [comment]
We will investigate this again once `React.lazy` and `React.Suspense` are actually supported on the server side.
Until then we provide [`importComponent`](https://github.com/xing/hops#code-splitting-and-hopss-importcomponent-function) wich works on the client-side as well as the server-side (more detailed description here: https://github.com/xing/hops#importcomponentmodule-exportname)
