### ISSUE TITLE
Write tests for the prefetch-on-server feature

### ISSUE THREAD

**Issue by jhiode** [xing/hops#723]
## This is my intent (choose one)

- [ ] I want to report a bug
- [ ] I want to request a feature or change
- [x] I want to provide or change a feature

## The problem

We were able to introduce a bug in #703 without noticing.

## Proposed solution

Cover that feature in a (unit?) test.

**Comment by ZauberNerd** [comment]
We have a ticket about introducing unit tests in our internal back log and will tackle this issue as part of that task.
