### ISSUE TITLE
[RFC] Switch again to @babel/preset-typescript to fix issues 

### ISSUE THREAD

**Issue by robin-drexler** [xing/hops#765]
Our current typescript setup has some issues:

@matthias-reis reported problems with HMR. According to [`ts-loader` docs](https://github.com/TypeStrong/ts-loader/tree/master/examples/hot-module-replacement#note), HMR only works properly when `transpileOnly: true` is set to true, which we did not do in hops-typescript.

Even worse maybe is the fact that `.tsx?` files are not touched by babel at all which means you end up with es-next code and missing polyfills in your bundle.

Both of those issues could be fixed, if we switched to [`@babel/preset-typescript`](https://babeljs.io/docs/en/babel-preset-typescript). 

[We already had this once and got back to `ts-loader`](https://github.com/xing/hops/pull/614) due to issues we experienced and the fear the preset would always lack behind `ts-loader`. 

While this still holds true, large and popular frameworks like `create-react-app` ([webpack config](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L347), [custom babel preset](https://github.com/facebook/create-react-app/blob/master/packages/babel-preset-react-app/create.js#L110)) and `gatsby` ([custom gatsby babel plugin](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-typescript/src/gatsby-node.js#L5)) seem to successfully use the `@babel/preset-typescript `.

So maybe we should give it another go?

We could of course also fix our currentlu known issues by other means (e.g. by adding babel-loader after ts-loader for `.tsx?` files), but maybe we should just embrace the babel-preset.

What do you think?

**Comment by ZauberNerd** [comment]
Can you clarify what issues @matthias-reis is seeing with HMR? It's working fine for our side project (https://github.com/foosbyte/kicker-trainer).

By setting `transpileOnly: true` we lose all type checks and would then need to set-up the `fork-ts-checker-webpack-plugin` (https://github.com/TypeStrong/ts-loader#transpileonly-boolean-defaultfalse).

I hadn't realised that babel doesn't work on `.tsx?` files, but I just tested it out and its true there's no polyfilling whatsoever happening.. Which also means that our code splitting support with `importComponent()` won't work in a typescript setup :/

I'm against switching from `ts-loader` to `@babel/preset-typescript` because that would be a breaking change and I think we should get our own setup correct first.

Another thing that we *could* do, would be to switch to `@babel/preset-typescript` via an environmental variable `ENABLE_EXPERIMENTAL_BABEL_TS_SUPPORT=true` or something similar.

**Comment by herschel666** [comment]
I agree with @ZauberNerd here: switching to `@babel/preset-typescript` was a breaking change we might not want.

It also seems as if the HMR example over at the ts-loader repo was out of date ([source](https://github.com/TypeStrong/ts-loader/issues/781#issuecomment-391797553)).

So I would argue in favour of keeping the ts-loader and sending its output through the babel-loader.

**Comment by herschel666** [comment]
Also the `importComponent` function apparently doesn't work with the current setup. It seems to be fixed though, when the compiled Typescript is piped through the babel-loader. So I would propose we add the babel-loader to the Typescript/Webpack setup and sell it as a fix for code-splitting. 😛

**Comment by robin-drexler** [comment]
>  So I would propose we add the babel-loader to the Typescript/Webpack setup and sell it as a fix for code-splitting. 😛

Not sure if you are joking, but adding the babel loader for `.tsx?` will not fix the issues  with the `importComponent` as described in #758 at all.

Nevertheless, if we want to keep `ts-loader` in place, we ought to add `babel-loader` to ensure transpilation (including stuff for `importComponent`) and polyfill handling actually happens.

**Comment by matthias-reis** [comment]
When fixing this issue, you might also want to consider full CSS Modules support (probably a separate ticket) as it is a first class citizen in the hops environment. Currently it only works with `require()` and an additional line of tslint or manual `.d.ts` files.

[See this article for more details](https://medium.com/@sapegin/css-modules-with-typescript-and-webpack-6b221ebe5f10) and the (oops ... just recognized Jimdo owned) [typescript css loader](https://github.com/Jimdo/typings-for-css-modules-loader)

**Comment by herschel666** [comment]
@matthias-reis The `typings-for-css-modules-loader` can really slow things down. And not everybody prefers type-safety and autocompletion on CSS classnames over having the shortest possible incremental build time.

Therefor I would propose to provide a how-to that describes how to setup the `typings-for-css-modules-loader`, but not include it by default.

**Comment by matthias-reis** [comment]
Fine for me. @herschel666 I guess you know the loader plugin?
