### ISSUE TITLE
Onboarding Improvements

### ISSUE THREAD

**Issue by dmbch** [xing/hops#783]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

Running `npx create-hops-app my-hops-app` or `yarn create hops-app my-hops-app` as proposed in our README certainly works as intended, but quite a lot of peer dependency warnings are being printed to the console. In my opinion, this is rather unfortunate and not quite the onboarding experience we ought to strive for.

## Proposed solution

Alter `create-hops-app` in a way that ensures no (misleading) warnings are being printed (similar to `create-react-app`).

**Comment by ZauberNerd** [comment]
This has landed in master with #785 and will soon be released as latest.
