### ISSUE TITLE
How do I pass data from express to react using hops?

### ISSUE THREAD

**Issue by saviomuc** [xing/hops#802]
I want to use express to evaluate the user agent string (i.e. to check if a request comes from a mobile device) and pass this information to the view.

The setup looks like this:

```
mixin.core.js:

 configureServer(app, middlewares, mode) {
    app.use((req, res, next) => {
      // my code
      next();
    });
  }
```

However I struggle to understand how to pass the information I got from parsing the request into the view. I'd prefer a solution which passes props.

The documentation mentions `withServerData` but no info on how to use it. I could also mutate `this.config` and use `withConfig` hoc but that feels dirty. 
Do you have some recommendation or hint on how to achieve that?

**Comment by ZauberNerd** [comment]
I would propose to store the information you need into express' `res.locals` in your core mixin and then use them with serverData in a browser/server mixin:

`mixin.core.js`
```
configureServer(app, middlewares, mode) {
  middlewares.initial.push((req, res, next) => {
    res.locals.isMobile = somethingWithRequest(req);
  });
}
```

`mixin.server.js`
```
enhanceServerData(data, req, res) {
  return { ...data, isMobile: res.locals.isMobile };
}
```

`my-component.js`
```
const MyComponent extends React.Component {
  render() {
    return <h1>{this.props.serverData.isMobile}</h1>
  }
}
export default withServerData(MyComponent);
```

**Comment by saviomuc** [comment]
Nice! Love it. Do you mind if I create a PR which explains this workflow? Not sure if this is too specific but I feel other users might be interested as well. Otherwise we can close the issue.

**Comment by ZauberNerd** [comment]
@saviomuc yes, that would be great.
I assume you will be adding it to the advanced examples section? https://github.com/xing/hops#configuring-expressjs-through-a-core-mixin

We also have [this bit](https://github.com/xing/hops#withserverdatacomponent) in the main readme about the `withServerData` HoC, but I suppose it should have a link pointing to: https://github.com/xing/hops/tree/master/packages/react#withserverdatacomponent-higherordercomponent and possibly to: https://github.com/xing/hops/tree/master/packages/react#enhanceserverdataserverdata-req-res-serverdata-pipe-server

**Comment by saviomuc** [comment]
@ZauberNerd 

I like the suggestion however I was also thinking about linking internally from  [withServerData](https://github.com/xing/hops#withserverdatacomponent) to the new documentation bit, which would be below [here](https://github.com/xing/hops#configuring-expressjs-through-a-core-mixin). This would probably be called: `Example: Passing data from server to a React component`.

From there I'd like to link to respective [withServerData](https://github.com/xing/hops/tree/master/packages/react#withserverdatacomponent-higherordercomponent)  and [enhanceServerData](https://github.com/xing/hops/tree/master/packages/react#enhanceserverdataserverdata-req-res-serverdata-pipe-server) documentation bits. 

This would make the reading flow a little bit more linear. What do you think?

**Comment by ZauberNerd** [comment]
@saviomuc sure, go ahead :)

**Comment by ZauberNerd** [comment]
Closed via https://github.com/xing/hops/pull/847
