### ISSUE TITLE
HMR is broken with latest untool

### ISSUE THREAD

**Issue by dmbch** [xing/hops#817]
## This is my intent (choose one)

- [x] I want to report a bug
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

Currently browser HMR is broken because arg validation is triggered. An untool fix release is pending.

## Proposed solution

Update to upcoming untool version and release all the things... See https://github.com/untool/untool/pull/288

**Comment by Xiphe** [comment]
### Steps to reproduce

 - create new hops app (`npx create-hops-app my-new-hops-project`)
 - start app `npm start`
 - see working app in browser
 - change something in `app.js`
 - see console in browser

**Comment by Xiphe** [comment]
Thanks for the fast reaction <3

**Comment by dmbch** [comment]
🚢 Fix published in `@untool/webpack` v1.3.1

**Comment by herschel666** [comment]
Resolved by [`870b3ca`](870b3ca2755f8e0249087c6e21c8074444853718)
